### ISSUE TITLE
If mqtt target provider is necessary?

### ISSUE THREAD

**Issue by yanjiaxin534** [eclipse-symphony/symphony#368]
I don't know if mqtt is necessary. When we will use mqtt.

**Comment by msftcoderdjw** [comment]
One scenario I know is mqtt target provider usually works as proxy provider to connect with remote target provider (e.g. we can run symphony-api as standalone service). Do we have other use cases for mqtt target provider? Seems we need the publisher/subscriber to generate/consume the symphony internal deployment artifacts, which is not as that common as http target provider.

+ @Haishi2016 , Haishi, would you please comment on this?

**Comment by Haishi2016** [comment]
MQTT target provider turns out to be VERY important. We need to invest more in it to make it work reliably. Like @msftcoderdjw  methoed, MQTT target provider serves as a proxy provider that allows us to delegate state seeking operations to a remote provider, which is actually quite common in many customer deployment topologies.

**Comment by msftcoderdjw** [comment]
In maestro, launch symphony agent with a MQTT broker address. MQTT binding will be inited. Then mqtt target provider can be worked as proxy.
