### ISSUE TITLE
Catalog should not be created without catalogType

### ISSUE THREAD

**Issue by linyguo** [eclipse-symphony/symphony#527]
Catalog can be created successfully without catalog type:
![image](https://github.com/user-attachments/assets/afd8e189-ba6b-4c1a-8010-dc9fa544c045)
![image](https://github.com/user-attachments/assets/92417419-9970-49a5-abca-9b83ae3b9b88)

When get this catalog, its catalog type is empty.
![image](https://github.com/user-attachments/assets/b121275c-8d59-4a1d-8cf4-05e40adb24f7)

**Comment by lirenjie95** [comment]
![image](https://github.com/user-attachments/assets/de960c58-b9ba-4d5d-8b32-2cc947fd4d8b)
Both `catalogType` and `properties` are not required now, in order to allow user to create an empty catalog and update it later.
@FireDefend please correct me if I'm wrong.

PS: this is not an OSS related issue.
